sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
